name: flutter_getx_starter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  font_awesome_flutter:
  freezed_annotation: 
  dio: 
  flutter_secure_storage: 
  shared_preferences: 
  logger: ^1.1.0
  cupertino_icons: ^1.0.2
  get: 4.6.1
  youtube_player_flutter: 8.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: 
  freezed: 
  json_serializable:
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
  - assets/json/

